# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool: Default

variables:
  buildConfiguration: 'Release'
stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
        - checkout: self
          submodules: true
        - task: DotNetCoreCLI@2
          inputs:
            command: 'restore'
            projects: '**/*.csproj'
            feedsToUse: 'select'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            configuration: $(buildConfiguration)
            projects: '**/*.csproj'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'publish'
            publishWebProjects: false
            arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Build.ArtifactStagingDirectory)'
            artifact: 'Xivapi.Discord.Bot'
            publishLocation: 'pipeline'
  
  - stage: Deploy
    jobs:
      - deployment: Deploy
        workspace:
          clean: all
        environment: Live
        strategy:
          runOnce:
            deploy:
              steps:
              - task: DownloadPipelineArtifact@2
                displayName: 'Download Artifact'
                inputs:
                  buildType: 'current'
                  artifactName: 'Xivapi.Discord.Bot'
                  targetPath: '$(Pipeline.Workspace)/Deploy'
              - task: FileTransform@1
                displayName: 'Tokenize Files'
                inputs:
                  folderPath: '$(Pipeline.Workspace)/Deploy/*.zip'
                  fileType: 'json'
                  targetFiles: '**/appsettings.json'
              - task: CopyFilesOverSSH@0
                displayName: 'Copy files to server'
                inputs:
                  sshEndpoint: 'Oracle Cloud'
                  sourceFolder: '$(Pipeline.Workspace)/Deploy'
                  contents: '**'
                  targetFolder: '/home/deployuser/deployments/xivapi'
                  cleanTargetFolder: true
                  cleanHiddenFilesInTarget: true
                  readyTimeout: '20000'
                    